### ISSUE TITLE
Reatime_zshim RIRO coefficient scaled by the RMS of the PMU pressure

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#160]
During realtime zshimming, we need to fit the pressure and the fieldmap/gradient. This is done with a linear regression where : `gradient(iVox)= Corrections.static( iVox ) + ( PMU_current_value - PMU_mean_value ) * Corrections.riro( iVox )`.
 In the matlab code, once the regression is done (static and riro are calculated for each voxel), the riro coefficent is multiplied by the RMS of the pressure. 

Here is the where the code is:
- (Eva's sanity check): https://github.com/shimming-toolbox/shimming-toolbox-matlab/blob/7f0ba2d480a697a16a0d4b20154c61171f7e13ca/example/realtime_zshim.m#L228
- Ryan's model field: https://github.com/shimming-toolbox/shimming-toolbox-matlab/blob/7f0ba2d480a697a16a0d4b20154c61171f7e13ca/Img/FieldEval.m#L865

Why is this the case? @rtopfer @evaalonsoortiz

**Comment by evaalonsoortiz** [comment]
I believe this is just a matter of preference for visualization, ie; when plotting static and RIRO correction maps, if the RIRO correction is scaled by the RMS_PMU_value, then you will see what the typical range of RIRO corrections is when you actually apply them. If you scale the RIRO, you have to remember to "rescale" it back before saving the RIRO correction to a text file.

At one point, scaling RIRO by RMS_PMU_value had led to an error where we were erroneously rescaling twice. I removed it altogether but @rtopfer had a preference for keeping it for another reason. He commented on it somewhere on github I think, but for the life of me I can't find the issue/PR where it came up. @rtopfer Do you still want to keep it this way? If you don't have any strong reasons, I would eliminate it to keep things simple.

**Comment by rtopfer** [comment]
For the multi-coil arrays, we typically run up against hardware limits: there is only so much current to distribute across the channels. For static shimming, we're effectively saying "all available current goes toward correcting the static field component". Simple. 

But if the aim is to minimize 2 fields (e.g. the static and resp. component)—separately but simultaneously—how do you prioritize/allocate the limited available current between them? i.e. One needs to assign weighting factors to each component. 

The reasonable default, which is embodied in the MATLAB code, is to weight them according to their respective _net_ contributions over the "training" time series, i.e. according to the relative power of the static (DC) and respiratory (time-varying) fields. This is achieved by scaling the resp. field component to correspond to the mean square deviation of the PMU recording (the static field receives a weighting of unity).

If you're only optimizing the gradient terms, you're unlikely to run into hardware limits, in which case, the selective weighting won't matter. But for the multi-coil case, this default weighting scheme seems like the natural (simplest) choice: it's not just to make the two field components comparable (same units, for visualization), rather, it serves to make the optimized DC+dynamic shim coefficients _commensurate_ to the field effects they're meant to correct.

**Comment by rtopfer** [comment]
can't find the GitHub discussion either but I remember mentioning this point previously: the initial scaling of "RIRO" upon fitting is essentially arbitrary: tightening the belt of the sensor won't change the field variation (unless you _really_ tighten it 😬) but it will reduce the scaling of the fitted Hz/unit-PMU RIRO map.
To have any way of comparing measurements one subject to the next, one needs to account for this, i.e. by scaling in the manner mentioned above, or by the peak-to-peak PMU variation (provided they aren't clipped), or by some other measure...

For the python implementation, you can certainly have the field fitting stage return RIRO coefficients as a map in Hz/unit-PMU, but you'll likely need to return & retain additional PMU measures in order to normalize them at some later point. IMO it's more intuitive (easier to sanity-check) to work with a field measure that has been abstracted from the arbitrary scale of the sensor readings, even though the RIRO shim coefficients, once optimized, will need to be scaled as such (e.g. mA/unit-PMU)

**Comment by po09i** [comment]
> To have any way of comparing measurements one subject to the next, one needs to account for this, i.e. by scaling in the manner mentioned above

I see.. when comparing results across scans, this allows to have a comparison on the same scale. The RMS coefficient `GzField.Model.Riro.Aux.Data.p` [here](https://github.com/shimming-toolbox/shimming-toolbox-matlab/blob/7f0ba2d480a697a16a0d4b20154c61171f7e13ca/example/realtime_zshim.m#L363) is then used to scale back to the appropriate unit expected for the scan of the same session.

**Comment by po09i** [comment]
Issue can be closed, this was a question for #134 which got merged.
