### ISSUE TITLE
Limit file size on commit

### ISSUE THREAD

**Issue by alexfoias** [shimming-toolbox/shimming-toolbox#199]
Problem: we would like to forbid commits that include files bigger than XX MB.
Possible implementations: 

- https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit/39578014#39578014
- https://gist.github.com/kiwidamien/a6a909ee196be8795b30431079074d64

Crossref: https://github.com/neuropoly/spinalcordtoolbox/issues/3100 https://github.com/neuropoly/axondeepseg/issues/423 https://github.com/ivadomed/ivadomed/issues/583

**Comment by kousu** [comment]
https://github.com/neuropoly/spinalcordtoolbox/issues/2705

**Comment by jidicula** [comment]
What about using [pre-commit](https://pre-commit.com) as a development dependency? It has an out-of-the-box hook for large file sizes: https://github.com/pre-commit/pre-commit-hooks#check-added-large-files . The project's hooks are defined in a `.pre-commit-config.yaml` file at the root of the repo, and each developer only has to run `pre-commit install` once to set up the tool locally.

**Comment by kousu** [comment]
I think that's a good idea too, but I was envisioning anything like that as a complement to server-side enforcement. Anything that's not enforced will be skipped by at least some people on some machines at least some of the time, and I fear that the rarer we make it the less obvious it will be to repair when it does happen.

**Comment by jidicula** [comment]
I've actually set this up in a GitHub Actions workflow on the serverside (command is `pre-commit run --all-files <hookname>`) for another project (in a private repo), but the caveat is that once it's caught on GitHub, the commits are already made (on the feature branch) and the contributor has to figure out how to rebase, which has been a pretty tough step in this team so far.

I think it would be easiest to add pre-commit in setup.py as an `extras` dependency, the same way we optionally require Sphinx and related packages for locally building documentation. https://github.com/shimming-toolbox/shimming-toolbox/blob/bd934ff17d8fba6ca79ef93538515849d3b990c8/setup.py#L49

At the very least, we're [blocked from pushing anything larger than 100MB by default](https://docs.github.com/en/github/managing-large-files/conditions-for-large-files#blocked-pushes-for-large-files), but there doesn't seem to be any feature to set a lower limit within GitHub 😦 

So, maybe a 2-prong approach?
- pre-commit as an extra dependency
- GH Actions workflow to run pre-commit serverside to check all pushes for large files (and broken ASTs, which can also be added in a pre-commit config). If the large file check fails, a more experienced dev has to step in and help the contributor clean up their history.

**Comment by kousu** [comment]
That's a good insight, that there's no way to *stop* a large file from ending up on the server because Github provides no hook we sneak in with. So any server-side solution will be half-baked ultimately.

In [SCT](https://github.com/neuropoly/spinalcordtoolbox/issues) we have a policy of squashing all PRs, both so that work is done in units of a PR, and with the intentional side-effect that undoing and particularly deleting large accidental files get forgotten. A squash is a rebase, but it's hidden behind a button on Github so it's easier to use. I take it you're doing the same thing here?

In fact I know you are:

![screenshot of mandatory squashing](https://user-images.githubusercontent.com/987487/105638680-f880ae00-5e41-11eb-8526-75ba2530279a.png)

In that case, we could sidestep the difficult rebase UI by just reporting "hey you have these large files.... please `git rm` them" and running the check on the *diff* between `master` and the feature branch, and making it a required check before the branch can be merged.

Because we're sharing a repo instead of using forks, this does mean that for the duration of the branch the large files will lag out CI and dev for everyone. To prevent that entirely we would need to have the server-side Action do its own commit surgery, which I am theoretically interested in seeing if possible but which I would trust at least ability to get right.

**Comment by kousu** [comment]
I kind of like that https://stackoverflow.com/a/39578014/2898673 is short and pure-shell. We could emulate `pre-commit install` without python [as simple as](https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/) 

```
#!/bin/sh
find .githooks -type f -exec ln -sf ../../{} .git/hooks/ \;
```

**Comment by kousu** [comment]
But generally: two pronged approach :+1:  :+1: :+1:
