### ISSUE TITLE
Implement a function to load the RF fieldmaps

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#210]
### Feature Description:

In order to perform RF-shimming, the first step is to load the acquired B<sub>1</sub> maps in the toolbox.
Due to a problem in the conversion from `dicom` to `nifti` mentioned in #58 , we decided for now to directly start from a `nifti`  file that is returned when running dicom_to_nifti with the folder containing the dicoms acquired using the RF-mapping sequence (turbo flash sequence on a 7T Siemens Magneton Terra). 

### Implementation Suggestion:

In order to load these maps, the main idea is to be as close as possible to what `load_nifit` and `prepare_fieldmap` are currently doing for B<sub>0</sub>, especially in terms of output, cli and testing. 

Regarding the organization of the different files in the toolbox, we would go with what is mentioned [here](https://github.com/shimming-toolbox/shimming-toolbox/issues/208#issuecomment-763047514), with the separation of the code in two folders `b0` and `b1`, and with overlapping functions at the root.

**Comment by gaspardcereza** [comment]
@po09i Do you think the re-organization of the code should be a specific issue ?

**Comment by po09i** [comment]
I think a refactoring in its own PR for the B0 stuff will be needed soon. For now, to get you started, I think you should start working on the B1 stuff and organize it as we mentioned [here](https://github.com/shimming-toolbox/shimming-toolbox/issues/208#issuecomment-763047514). In theory all the code you will use for B1 should not get refactored since it is not B0 specific. If you have more questions or realize a seperate issue for the organization is relevant then go ahead and I can try to help with the specifics.
