### ISSUE TITLE
GitHub Actions: Cache SCT in our CI tests workflow

### ISSUE THREAD

**Issue by jidicula** [shimming-toolbox/shimming-toolbox#216]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Document the use of config/dcm2bids.json*)
- [x] I've given this issue the correct labels

### Description of Problem / Inefficiency:
Currently, Spinal Cord Toolbox installation is the bottleneck in our CI tests that are run on each PR. Even on the fastest build matrix option, Ubuntu 20.04 on Python 3.8, [SCT installation step takes around 2m16s](https://github.com/shimming-toolbox/shimming-toolbox/pull/215/checks?check_run_id=1798130049#step:8:1).

### Implementation Suggestion:

This can easily be fixed by caching its install location, then only running its install step in the GH Actions workflow if the cache hit does not occur. However, before I start on that enhancement, I would like to understand how SCT is being used:

1. What version of SCT needs to be installed in CI? Does it need to be pinned, or should we continue always building the HEAD version of SCT on every PR in shimming-toolbox?
2. Is SCT a soft dependency? If so, should we create a build matrix to run tests with and without it?

### Additional Context / Screenshots:

N/A

**Comment by po09i** [comment]
@jidicula I think this is a great idea, the installation does take quite some time. 

1. We are using the latest version of SCT right now, using the HEAD version we will be able to get the latest release but will most likely need to maintain it a bit more. Since SCT is constantly evolving, I think we should point to the HEAD so that users dont have to downgrade SCT or have two versions if they are already use SCT. I'm open to other opinions.
2. SCT is being used during masking to segment the spinal cord. It is a soft dependency.

I'll briefly mention that PR #164 will add some sct handling within pytest (sct marker, etc)

**Comment by jidicula** [comment]
Ok, so since we want it to depend on SCT HEAD, I'll configure the caching to use the commit hash at HEAD as the cache key - if the hash changes, the cache is invalid and SCT has to be reinstalled.

At the very least, this will save some CI build time when a PR has multiple cycles of commit, request changes, commit.
