### ISSUE TITLE
Uniformity of the README and help of the commands

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/shimming-toolbox#274]
In the README there isn't a list of all st_ commands and the example it links don't show all of them. It would be nice to add a list of all the commands accessible in the README.rst

Futhermore, the "st_mask -h" command give the different commands but not their parameters (ex: the box comand need -size -input -output but they aren't in the "st_mask -h")
The "st_prepare_fieldmap" doesn't have the [requiered] to the phase path input.

**Comment by jcohenadad** [comment]
> Futhermore, the "st_mask -h" command give the different commands but not their parameters (ex: the box comand need -size -input -output but they aren't in the "st_mask -h")

Because we use nested usage. To get the help you would need to do: `st_mask box -h`.

I've already had concerns in the past that this nested usage would be confusing for users not familiar with UNIX (which will likely be a non-negligible proportion of ST users). Maybe we should reconsider nesting...?  Or better explain how users can get help for specific command (maybe the latter option is better, given the advantage of nested usage: it is cleaner).

**Comment by KevinBerard** [comment]
By reflex I did `st_mask -box -h` instead of `st_mask box -h`. I suppose it is my bad on this.

**Comment by po09i** [comment]
> In the README there isn't a list of all st_ commands and the example it links don't show all of them. It would be nice to add a list of all the commands accessible in the README.rst

I agree, it would be beneficial to have a list of all the available commands.

> The "st_prepare_fieldmap" doesn't have the [required] to the phase path input.

This is because phase is an argument and not an option. This means it is required and does not require an option name (i.e. `-phase`) in front. The reason it is an argument is that it is the only way to have a non-specified number of inputs (you can have however many `phase path input` as you want). More info on click [options](https://click.palletsprojects.com/en/8.0.x/options/) and [arguments](https://click.palletsprojects.com/en/8.0.x/arguments/).
