### ISSUE TITLE
multiprocessing sometimes hanging

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#278]
### Environment details

- I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Branch: `ad/optimizer`

Operating System and version:

```
(st_venv) alex@Alexandres-MacBook-Pro shimming-toolbox % st_dump_env_info 
ENVIRONMENT INFO:
posix x86_64
Darwin 20.4.0
Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
CPython 3.7.9

CPU cores: Available: 8, Used by ITK functions: 0
RAM: Total: 16384MB, Used: 8490MB, Available: 5352MB

PACKAGE INFO:
0.1.0
```

### Bug Description
When using multiprocessing (specifically the multiprocessing in the coordinates.py file:resample_from_to()) it sometimes hangs and a keyboard interrupt (ctrl + c) needs to happen by the user to stop the process. The behaviour did not occur when launching test_sequential_zslice from the IDE but occured when launching pytest from the command line on my computer (BigSur). The bug can also be seen in these 2 commits on MacOs Catalina python 3.7: https://github.com/shimming-toolbox/shimming-toolbox/pull/253/commits/35ab6178cdf50e51313602c2ab22b462ea30a2c2 and https://github.com/shimming-toolbox/shimming-toolbox/pull/253/commits/a45ff8a3d9792b4676cc281666adf0d95d726417.

![Screen Shot 2021-06-09 at 12 49 08](https://user-images.githubusercontent.com/47249340/121396153-15b1a700-c921-11eb-970c-f89b971c9a81.png)

### Potential Reasons behind Bug:
https://stackoverflow.com/questions/55812213/multiprocessing-pool-hangs-on-running-program
Note that there is a ref to the following link in the comments which explains what I think is the bug but was fixed in python 3.8
https://bugs.python.org/issue33725

If this is really the case, we would need to drop support fo 3.7... 
For now multiprocessing is not necessary so I just commented the code out but this is something to think about later if we want to add multiprocessing.

Other threads I looked at:
https://github.com/gammapy/gammapy/issues/2453

**Comment by ahill187** [comment]
https://github.com/python/cpython/blob/3.9/Lib/multiprocessing/pool.py 

Not sure if this is related, but I ran into a similar problem with `ivadomed` with `test_automate_training.py`:

## Tests

One thing to note is that when testing any command line scripts that use multiprocessing, you should use `script_runner` to call the module instead of `script_to_test.main(args)`. This is because if you do the latter, the processes aren't closed between the tests in your script.

For example, let's say you have a script, `mp_script.py`:

```
import multiprocessing as mp
import time

def sleep_for_a_bit(seconds):
    print(f"Sleeping for {seconds} second(s)")
    time.sleep(seconds)
    print("Done sleeping!")
    print(mp.current_process())

def main():
    pool = mp.Pool(processes=2)
    pool.map(func=sleep_for_a_bit, iterable=[1 for i in range(0, 2)])
    pool.close()    

if __name__ == "__main__":
    main()
```

Let's say you want to test this script using `script_to_test.main(args)`:

```
import mp_script

def test_mp_script_a():
    mp_script.main()


def test_mp_script_b():
    mp_script.main()
```

If you run this test, you will get something like:

```
Sleeping for 1 second(s)
Sleeping for 1 second(s)
Done sleeping!
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-1' parent=91203 started daemon>
<SpawnProcess name='SpawnPoolWorker-2' parent=91203 started daemon>
Sleeping for 1 second(s)
Sleeping for 1 second(s)
Done sleeping!
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-4' parent=91203 started daemon>
<SpawnProcess name='SpawnPoolWorker-3' parent=91203 started daemon>
```

Note how between the two separate tests, `test_mp_script_a` and `test_mp_script_b`, the SpawnPoolWorkers aren't resetting? In this example, the tests would pass fine, because the script isn't doing anything other than sleeping. However, if your script relies on the processes to be distinct, there could be a problem.

To correctly test, you will need to use `script_runner` from `pytest-console-scripts`:

```
import pytest

@pytest.mark.script_launch_mode('subprocess')
def test_mp_script_a(script_runner):
    ret = script_runner.run('mp_script')
    print(f"{ret.stdout}")
    print(f"{ret.stderr}")
    assert ret.success

@pytest.mark.script_launch_mode('subprocess')
def test_mp_script_b(script_runner):
    ret = script_runner.run('mp_script')
    print(f"{ret.stdout}")
    print(f"{ret.stderr}")
    assert ret.success
```

If you run this test, you should see something like:

```
Sleeping for 1 second(s)
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-1' parent=91378 started daemon>
Sleeping for 1 second(s)
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-2' parent=91378 started daemon>

Sleeping for 1 second(s)
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-1' parent=91378 started daemon>
Sleeping for 1 second(s)
Done sleeping!
<SpawnProcess name='SpawnPoolWorker-2' parent=91378 started daemon>
```

As you can see, the SpawnPoolWorker is not being carried over between tests anymore.

**Comment by ahill187** [comment]
I tested the bug on my system:

OS: MacOS Big Sur
Python: 3.8.2
branch: ad/optimizer

Then I ran this 4 times consecutively with all tests passing:
```
pytest -s test_sequential_z_slice.py
```

**Comment by ahill187** [comment]
Found help here: https://github.com/matplotlib/matplotlib/issues/15410#issuecomment-625027757

Python 3.7 uses `fork` by default, which was causing it to break on 3.7 and not 3.8 (which uses `spawn`). So we added the line:
```
mp.set_start_method('spawn', force=True)
```
That fixed it 😄 

We had a similar issue in `ivadomed`: https://github.com/ivadomed/ivadomed/pull/580/commits/81c3dcd47f44a3a0899d19f121a46ac60dfa9663
