### ISSUE TITLE
FSLEYES not visible from inside st_venv

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/shimming-toolbox#342]
The fsleyes command does not return anything when called from within the st_venv virtual environment.

```
(st_venv) danielpapp@Daniels-MacBook-Pro ~ % fsleyes
zsh: command not found: fsleyes
```
```
(st_venv) danielpapp@Daniels-MacBook-Pro ~ % which fsleyes
fsleyes not found
```

Calling it from outside the venv works as intended:

```
(base) danielpapp@Daniels-MacBook-Pro ~ % which fsleyes
/Users/danielpapp/miniconda/bin/fsleyes
```

Online discussion implied this might have to do with conda vs miniconda in the PATH from within or outside the st_venv.

From within the venv:

```
(st_venv) danielpapp@Daniels-MacBook-Pro ~ % echo $PATH   
/Users/danielpapp/shimming-toolbox/bin
/Users/danielpapp/shimming-toolbox/python/envs/st_venv/bin
/Users/danielpapp/miniconda/condabin
/Users/danielpapp/spinalcordtoolbox/bin
/usr/local/fsl/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
```

From outside the virutal env:

```
(base) danielpapp@Daniels-MacBook-Pro ~ % echo $PATH   
/Users/danielpapp/shimming-toolbox/bin
/Users/danielpapp/miniconda/bin
/Users/danielpapp/miniconda/condabin
/Users/danielpapp/spinalcordtoolbox/bin
/usr/local/fsl/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Library/Apple/usr/bin
/Library/Frameworks/Mono.framework/Versions/Current/Commands

```

I think the difference is the lack of 
`/Users/danielpapp/miniconda/bin`
in the st_venv, but I do not know if this is intentional or not.

OS/program versions:
Mac Catalina 10.15.7
Conda version 4.10.1
FSLeyes version: 1.0.3

**Comment by jcohenadad** [comment]
that sounds vaguely familiar and something we might have encountered with SCT @joshuacwnewton @kousu and/or ADS @mathieuboudreau

**Comment by joshuacwnewton** [comment]
From a cursory glance here, it looks like you've installed `fsleyes` into your `(base)` conda environment. If that's the case, then what you've observed is expected behavior as far as conda goes. This is because activating the `(st_venv)` conda environment has the side-effect of deactivating the currently-active conda environment (related: https://github.com/conda/conda/issues/3580, https://github.com/conda/conda/issues/2502) -- `(base)` is no longer active, hence the PATH change you noticed. 

To fix this, what I like to do personally when it comes to a conda-installed fsleyes is explicitly creating a symlink to the `fsleyes` binary inside of [`/usr/local/bin`](https://unix.stackexchange.com/questions/4186/what-is-usr-local-bin), so that `fsleyes` is always accessible regardless of which conda environment is activated. You can do this by running:

```
sudo ln -s ~/miniconda/bin/fsleyes /usr/local/bin/fsleyes
```

But, it might be good to double-check the installation instructions for ST to see if there are other ways we can help our users avoid this pitfall.

**Comment by po09i** [comment]
> From a cursory glance here, it looks like you've installed fsleyes into your (base) conda environment.

You can validate by trying to launch fsleyes outside of conda entirely. Navigate to the base environment then: 

```
conda deactivate
fsleyes
```

**Comment by jcohenadad** [comment]
thank you for chipping in @joshuacwnewton !

**Comment by dpapp86** [comment]
@joshuacwnewton : You have correctly identified the issue, and the solution. Now, fsleyes can be seen from within the st_venv, as well as from outside of (base).
Kudos!
