### ISSUE TITLE
Speed up B0 shimming

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#412]
### Description of Problem / Inefficiency:
B0 shimming is important but also needs to be fast. 

We currently have 2 main solvers to process and find the currents that best fit B0 maps. Both solvers can be found in the shimmingtoolbox/optimizer.
- [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) (SLSQP)
  - Allows to input constraints, slower
- pseudo inverse
  - No constraints, faster

We would like to make things faster while also respecting coil constraints.

### Implementation Suggestion:
Along with the current implementation, some previous work had been done in Matlab which could be a useful reference: [ST-matlab](https://github.com/shimming-toolbox/shimming-toolbox-matlab/blob/7f0ba2d480a697a16a0d4b20154c61171f7e13ca/Coils/Shim_Template/ShimOpt.m#L940)

### Additional Context / Screenshots:
Initial issue: #20

**Comment by po09i** [comment]
@Aurelienpujolm You can summarize your findings here. I have created a branch for you. You can access it by:
```
git fetch
git checkout ap/faster-solver
```

**Comment by Aurelienpujolm** [comment]
### **Description of problem inefficiency :** 
B0 shimming is important but also needs to be fast. 
For reference, using the django mac computer, shimming with 50 slices, and using 32 channel coil takes around 90 seconds which is too slow. 
Around 20 seconds is taken to get the shimming coefficients, by using the _scipy.optimize.minimize_, 36 seconds to plot figures and around 26 seconds to evaluate the static shim.

### **First suggestion :** 
I first suggest minimizing the time to get the shimming coefficient.

To do this,  I suggest changing the function to minimize from _residual_mae_ (which is using absolute values)  to  an equivalent _residual_mse_. Indeed the residual mse function should always be faster to minimize than the residual mae. Then adding a jacobian in the solver should also reduce the calculation time of _scipy.optimize.minimize._ (For one slice the calculation time can be divided by 10 using mse function and jacobian compare to the mse naive function) 

However, it can be possible to let the user choose which function he wants to minimize even if the optimization gives the same results with both functions.  

In addition, it should be interesting to let the user choose if he wants to use a multiprocessing solver or not. 
In my case, (so with a mac computer) I’ve chosen to remove the multiprocessing task from the optimizer since it was taking more time to open all of the cores than to do the optimization for each slice with only one of them . (Open all of the cores takes around 18 seconds and the calculation for each slice takes around 0.1 seconds). 

After all these modifications, on the django computer the optimization is now taking around 3 seconds which is seven times faster than before ! 
### **Description of problem inefficiency after the first suggestion :** 
However even with these modifications the total processing time would still be too high with a processing time of around 70 seconds. 
To do the B0 Shimming,  we are using the b0shim file in the cli class and the dynamic_cli function. Within this function and with the previous suggestion effectuated, two processes are taking most of the processing time  : 
Get shimming coefficients which takes around 32.8  seconds ( **46.8 % of the time**)
Plot a figure of the coefficients which takes around 36.2 seconds (**51.7 % of the time**)
_note : These numbers were get with the Django computer_ 
**Get the shimming coefficients** 
To get the shimming coefficients, we are using the _shim sequencer_ function from the sequencer class. 

The shim_sequencer function is divide in 3 parts : 
- Manipulate the input mask and the anatomical image to make sure that they have good properties. it takes around  3.5 seconds so 5 % of the total time 
- Optimizing slice by slice to get the coefficient takes around 3 seconds so 4 % of the total time (before it was 20 % of the total time)
- Evaluating the static shim takes around  26.2 seconds and so 37.8 % of the total processing time

So we need to reduce the processing time of the __eval_static_shim function_. 
We can divide this function in three parts that are taking most of the time : 

- Initialize values to plot them :  3.4 seconds 4.8 %
- Plot the figures : 1.5 seconds 2.1 % 
- Calculate the shimmed anatomic orientation :  21.2 seconds, so 30,2 % of the processing time 
So one of the functions to optimize to reduce the time of the program is the __cal_shimmed_anat_orient_ function. 

This function takes 8 seconds (11.3 %)  to resample the coil, and the anatomic fieldmap with the mask , and 13.2 seconds (18.7 %) to calculate the shimmed anatomic orientation.

    shimmed_anat_orient = np.zeros_like(fieldmap_anat)
    for i_shim in range(len(slices)):
        corr = np.sum(coefs[i_shim] * coils_anat, axis=3, keepdims=False)
        shimmed_anat_orient[..., slices[i_shim]] = fieldmap_anat[..., slices[i_shim]] + corr[..., slices[i_shim]]`

  _Code to calculate the shimmed anatomic orientation_ 

**Plot a figure of the coefficients**  

Then for the other part which is to plot a figure of the coefficients calculated just before. (51.7 % of the time). To do this, only one function is taking a long time, and this function is the _plot_coefs function within bo_shim class

This function has a process time of 36.2 seconds
11.39 seconds to plot the coefficients (16.3 %)
24.8 seconds to save the plotting figures (35.4 % ) 

The figure to plot is define like this :  
```
    n_shims = static_coefs.shape[0]
    fig = Figure(figsize=(8, 4 * n_shims), tight_layout=True)
```
_Code to initialize the plot_ 
The size of the figure will be (8,200) here because there are 50 slices in my case. And there will be subplots for each slice (even if there is no correction). 

The figure will then be save like this 

```
    fname_figure = os.path.join(path_output, f"fig_currents_per_slice_group_coil{coil_number}_{coil.name}.png")
    fig.savefig(fname_figure, bbox_inches='tight')
    logger.debug(f"Saved figure: {fname_figure}")
```
We would like to improve the time of the B0 shimming and so reduced the time of the function that was described above as time consuming 


### **Implementation suggestion :** 


__cal_shimmed_anat_orient_ 
For this function, the resampling part can’t seem to be improved in a simple way. However, I do think that the second part can maybe get faster

__plot_coefs_
For this function I can see three possibles ways of improved it : 

- If the correction to apply for one slice is null then, we shouldn’t plot the figure corresponding to that slice (However in the end, it should be possible to add a figure that combined all of the slices that haven’t got any corrections). In the data used in this example more than 50 % of the slices do not have any corrections
- It should maybe be interesting to save each sub plot for each slice in a different file. Indeed, now all of the subplot is in the same file, which makes the file huge, and not really visual. So if we are putting each subplot in different files it can make them more visual, and maybe faster ?
- Use multiprocessing

**Comment by po09i** [comment]
- We should provide the user the voice to use MAE, MSE, etc.. This is already a PR: #405, we can use MSE as default
- Multiprocessing has been a problem in the past, but 18 seconds of overhead is odd. We have resolved a lot of issues before but there might still be some left.
