### ISSUE TITLE
logger vs. logging vs. print

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#44]
In ST we don't have (yet) a standard way to display stdout on the Terminal. Should we use print() (as in SCT) or logging?  

And if we do use the logging, should we go with the "logger" approach or the straight up "logging".

Any preference between:

- logging, as used [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/logging#code-in-librarys-apis-eg-spinalcordtoolboxresampling)

- logger, with the necessary `logger = logging.getLogger(__name__)` at the beginning of each file?

i'm more in favour of the former, just because we don't need to declare a new variable for each python file.

**Comment by gab-berest** [comment]
I have used the logging library quite a lot in my projects. It is easy to log and easy to link logger together. It is also quite customizable (output log in command prompt and log file, colors, syntax of log with date, etc.). I'm in a favor of this one on my part.

**Comment by jcohenadad** [comment]
@gab-berest we are using the logging library, the purpose of this issue is simply to discuss how to use it: calling the library function each time or a variable set at the beginning

**Comment by gab-berest** [comment]
Ha I see sorry. The variable set is useful since it helps to determine where the log comes from. The variable from getLogger will always return the same logger object. What it differentiates is the name that you give. It also gives acces to formatter and handler that can first format the log messages and then do appropriate work (like sending automatically a report when an error is detected). To better understand the log we could do something like this:
`logger = logging.getLogger("PMU")`
Second file:
`logger = logging.getLogger("dicom_to_nifti")`
Then in the log with the correct formatter, you will see a string like:
2020-05-21 > PMU > Loaded file
2020-05-21 > dicom_to_nifti > Loaded file

The first way of logging directly from the package works, if we don't want to do something advanced with the logger. If we want to make it more user friendly and automate some work with the logger, we will need the variable way. In the end, even if you have to declare a logger objetc, it is better viewed and a better way to do it the logger way.

**Comment by gab-berest** [comment]
The variable set is useful since it helps to determine where the log comes from. The variable from getLogger will always return the same logger object. What it differentiates is the name that you give. It also gives acces to formatter and handler that can first format the log messages and then do appropriate work (like sending automatically a report when an error is detected). To better understand the log we could do something like this:
`logger = logging.getLogger("PMU")`
Second file:
`logger = logging.getLogger("dicom_to_nifti")`
Then in the log with the correct formatter, you will see a string like:
2020-05-21 > PMU > Loaded file
2020-05-21 > dicom_to_nifti > Loaded file

The first way of logging directly from the package works, if we don't want to do something advanced with the logger. If we want to make it more user friendly and automate some work with the logger, we will need the variable way. In the end, even if you have to declare a logger object, it is better viewed and a better way to do it the logger way. It will be better on the long run.

**Comment by jcohenadad** [comment]
Reviving this thread: @ahill187 @joshuacwnewton do you have any insights on this topic? Should we use "logger" everywhere in the ST code, both in CLI scripts and API?

**Comment by joshuacwnewton** [comment]
### Short answer

I'd recommend using `logging` (not print statements) and to use `logger = logging.getLogger(__name__)`.

> i'm more in favour of the former, just because we don't need to declare a new variable for each python file.

If I'm being honest, it probably doesn't make _that_ much of a difference whether you choose `logging` or `logger`. The latter has an (admittedly) small benefit, but the effort required is small too, so :shrug:. 

The most important thing is just to avoid using `print` statements. :sweat_smile: 

### Long answer

Even though I recommend `logging`, there are some caveats here:

1. Some of the benefits of `logging` are only useful for proper Python packages, the kind that other developers `pip install` then build Python projects on top of. 
    * For example, if you use print statements, then that creates unavoidable noise for downstream packages. But, if you use logging, downstream packages can choose to turn off or filter your log messages.
    * However, ST [doesn't appear provide a PyPI package](https://shimming-toolbox.org/en/latest/getting_started/installation_st/linux.html#install-from-github), and is used via CLI scripts (not a Python API). So, the "developer" kinds of benefits aren't as relevant for ST.
2. [Other benefits of logging](https://stackoverflow.com/a/6918596/7584115) (e.g. configurable log levels, log message formatting, filtering, etc.) aren't free, and do require some planning/coordination/dev work to get value from. 
    * Example 1: To make the most of log levels, ST would have to expose log level settings in the CLI via, for example, a `--verbose` option, and there would have to be enough to a difference between log levels for the user to find the setting meaningful enough to want to use it. (Not guaranteed!)
    * Example 2: To make the most of logging to a file, you would need a use-case where it makes more sense than logging to stdout, then you would need to configure paths, communicate that to the user, etc.
    * So, without building and maintaining that extra structure around the log messages, `logging` is effectively just the same as `print` as far as ST's users are concerned.

Despite the caveats, I think it's still good to stick with `logging`, even if ST doesn't use all of the features. 

* Worst case scenario, ST uses `logging` -> doesn't really get much benefit from it over `print` -> but didn't really put in much effort in the first place, since IIUC we would be making the decision pretty early on.
* Best case scenario, it saves ST a big refactor if one day down the line some of the features _do_ become relevant. (Since, if the `logging` statements are already in place, it's easy enough to incrementally take advantage of its features.)

**Comment by jcohenadad** [comment]
Thank you _soooo_ much for the thorough insights @joshuacwnewton, it is a convincing argument to go with logging indeed!

> However, ST doesn't appear provide a PyPI package, and is used via CLI scripts (not a Python API). So, the "developer" kinds of benefits aren't as relevant for ST.

it is our plan at some point though to have ST pip-installable

**Comment by po09i** [comment]
Thanks for the feedback! This makes a lot of sense! logging seems to be the way to go
