### ISSUE TITLE
dcm2niix not found if conda environment is not activated

### ISSUE THREAD

**Issue by 4rnaudB** [shimming-toolbox/shimming-toolbox#518]
### Environment details

- [ ] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

### Bug Description
dcm2niix is not found if the conda environment is not activated. The error persists even after using source `$HOME/shimming-toolbox/python/etc/profile.d/conda.sh`. Only running `conda activate ~/shimming-toolbox/python` before using any scripts using dcm2niix prevents the error from happening.

**Comment by po09i** [comment]
#### Context
Shimming Toolbox uses launchers (a copy of the CLI functions in a folder that we add to the path). `st_dicom_to_nifti` (CLI) makes a call to `dcm2bids` (API) which calls `dcm2niix` (CLI). `Dcm2bids` is installed from the "setup.py" file and `dcm2niix` is installed through a Conda call in the installer script.

`Dcm2niix` needs to be called from the command line. To launch `dcm2niix`, `dcm2bids` uses a call to the [subprocess](https://docs.python.org/3/library/subprocess.html) function. However, if the ST environment is not activated when making the `st_dicom_to_nifti` call, `dcm2niix` is not found because it is not in the PATH because subprocess seems to use the environment from when the `st_dicom_to_nifti` was launched from (not the ST environment). Now we do not want the users to have to change their environment everytime they want to use ST, so this is a problem.

Note: The Bids API does not have options to allow to change the environment ("env" when calling subprocess).

#### Goal
- Try to be as pythonic as possible
- The user should not have to do extra steps to use ST
- Easily maintainable

#### Solutions
I see solutions, all of which do not seem ideal:
1. Copy the dcm2niix binaries to the Shimming Toolbox launcher folder (dcm2niix becomes available everywhere, potentially creating version conflicts, we also don't control which version will be used)
2. Create a wrapper shell script that activates the Shimming Toolbox environment and launches `st_dicom_to_nifti` (I tested this solution and it works, not pythonic, weird to maintain)
3. Subclass dcm2bids and rewrite the subprocess call to dcm2niix to include the Shimming Toolbox environment (We would likely need to pin a version of dcm2bids, hard to do version upgrade to dcm2bids)

Are there other solutions that you see. If not, do you have a solution that you prefer.
@joshuacwnewton, @mguaypaq, @namgo, @nullnik-0

**Comment by joshuacwnewton** [comment]
I think @po09i has written an excellent summary. This is a tricky problem, due to a number of factors:

- `dcm2bids` expects `dcm2niix` [to be on the `PATH`](https://unfmontreal.github.io/Dcm2Bids/3.1.1/get-started/install/#dcm2niix). (See also: [`dcm2niix_version`](https://unfmontreal.github.io/Dcm2Bids/3.1.1/dcm2bids/utils/tools/?h=dcm2niix#dcm2niix_version))
- ST wants to take care of installing `dcm2niix` on behalf of users, so it builds its own conda environment and installs `dcm2niix` inside of it.
- ST also wants to avoid bleeding any `PATH` modifications outside of the ST environment.

> Note: The Bids API does not have options to allow to change the environment ("env" when calling subprocess).

Does `dcm2bids` pick up on changes to [`os.environ`](https://docs.python.org/3/library/os.html#os.environ)? For example, if you were to [modify the `PATH`](https://stackoverflow.com/a/1681244) within the ST Python script immediately prior to calling `dcm2bids`, would it be able to find `dcm2niix`? That way, we effectively get "Solution 1", but only in the context of the ST script (i.e. without affecting the user's system).

**Comment by namgo** [comment]
I'm not very familiar with the ST project so I'm sure I'm missing something... but as I was pinged I figured I'd ask:

Wouldn't it be more standard to build https://github.com/rordenlab/dcm2niix/ at the same time as the software is built on the user's system? Or are you trying to avoid library dependencies?

Edit: ah, Joshua mentioned on Slack how the installation process works! I misunderstood.

**Comment by po09i** [comment]
> Does dcm2bids pick up on changes to [os.environ](https://docs.python.org/3/library/os.html#os.environ)?

Yes! I tried it out and it works well, I'll test on windows when I have the chance!

Thanks @joshuacwnewton and @namgo!
